services:
  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_USER: rets
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: retsdb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - retsnetwork

  server:
    build: ./server
    environment:
      DATABASE_URL: ${DB_URL}
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - retsnetwork

volumes:
  db-data:

networks:
  retsnetwork:
