services:
  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_USER: rets
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: retsdb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - retsnetwork

  server:
    build: ./server
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DB_URL}
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 4000:4000
    depends_on:
      - db
    networks:
      - retsnetwork

volumes:
  db-data:

networks:
  retsnetwork:
